const SET_CATEGORIES = 'SET_CATEGORIES'
const SET_QUESTIONS = 'SET_QUESTIONS'
const START_LOADING = 'START_LOADING'
const STOP_LOADING = 'STOP_LOADING'

export default { SET_CATEGORIES, SET_QUESTIONS, START_LOADING, STOP_LOADING }
