const SET_CATEGORIES = 'SET_CATEGORIES'
const SET_QUESTIONS = 'SET_QUESTIONS'
const START_LOADING = 'START_LOADING'
const STOP_LOADING = 'STOP_LOADING'
const SET_API_TOKEN = 'SET_API_TOKEN'

export default { SET_CATEGORIES, SET_QUESTIONS, START_LOADING, STOP_LOADING, SET_API_TOKEN }
